<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAotCompatible>true</IsAotCompatible>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<RootNamespace>ToolBX.$(AssemblyName)</RootNamespace>
		<PackageId>ToolBX.$(AssemblyName)</PackageId>
		<Authors>Mathieu Moreault</Authors>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<RepositoryUrl>https://github.com/Moreault/Mathemancy</RepositoryUrl>
		<PackageProjectUrl>https://github.com/Moreault/Mathemancy</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Description>Basic collision classes</Description>
		<Version>4.0.0-beta.1</Version>
		<PackageIcon>collisions.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\collisions.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Mathemancy\Mathemancy.csproj" />
	</ItemGroup>

</Project>
